BRUSH_DICT = {
    "Add": "添加",
    "Comb": "梳理",
    "Delete": "删除",
    "Density": "密度",
    "Grow/Shrink": "增长收缩",
    "Pinch": "夹捏",
    "Puff": "蓬松",
    "Pull Tips": "拉直发稍",
    "Select": "选择",
    "Slide": "滑移",
    "Smooth": "平滑",
    "Airbrush": "喷枪",
    "Eraser Hard": "硬橡皮",
    "Erase Hard": "硬擦除",
    "Eraser Soft": "软橡皮",
    "Erase Soft": "软擦除",
    "Eraser Stroke": "画笔擦除",
    "Fill": "填充",
    "Ink Pen": "墨水笔",
    "Ink Pen Rough": "粗糙墨笔",
    "Marker Bold": "粗马克笔",
    "Marker Chisel": "平头马克",
    "Pen": "钢笔",
    "Pencil": "铅笔",
    "Pencil Soft": "软铅笔",
    "Tint": "色调",
    "Clone": "克隆",
    "Grab": "抓起",
    "Pull": "拉扯",
    "Randomize": "随机",
    "Strength": "强度",
    "Thickness": "厚度",
    "Twist": "扭曲",
    "Average": "平均",
    "Blur": "模糊",
    "Paint": "绘制",
    "Replace": "替换",
    "Smear": "涂抹",
    "Blend Hard": "硬混合",
    "Blend Soft": "软混合",
    "Blend Square": "方形混合",
    "Blob": "球体",
    "Boundary": "边界",
    "Clay": "粘土",
    "Clay Strips": "粘土条",
    "Clay Thumb": "指推",
    "Crease Polish": "折痕平滑",
    "Crease Sharp": "折痕锐化",
    "Drag Cloth": "拖拽布料",
    "Draw": "绘制",
    "Draw Sharp": "绘制锐边",
    "Elastic Grab": "弹性抓起",
    "Elastic Snake Hook": "弹性蛇钩",
    "Erase Multires Displacement": "擦除转换",
    "Expand/Contract Cloth": "布料伸缩",
    "Face Set Paint": "绘制面组",
    "Fill/Deepen": "填充加深",
    "Flatten/Contrast": "展平反差",
    "Grab 2D": "2D抓起",
    "Grab Cloth": "抓起",
    "Grab Planar Cloth": "平面抓起",
    "Grab Random Cloth": "随机抓起",
    "Grab Silhouette": "抓取剪影",
    "Inflate Cloth": "膨胀",
    "Inflate/Deflate": "膨胀收缩",
    "Layer": "平层堆积",
    "Mask": "遮罩",
    "Nudge": "推挪",
    "Paint Blend": "绘制混合",
    "Paint Hard": "软绘制",
    "Paint Hard Pressure": "硬感绘制",
    "Paint Soft": "硬绘制",
    "Paint Soft Pressure": "软感绘制",
    "Paint Square": "方形绘制",
    "Pinch Folds Cloth": "捏皱布料",
    "Pinch Point Cloth": "布料聚拢",
    "Pinch/Magnify": "夹捏放大",
    "Plateau": "台地平整",
    "Pose": "姿态变形",
    "Push Cloth": "推动布料",
    "Relax Pinch": "松弛捏合",
    "Relax Slide": "松弛滑移",
    "Scrape Multiplane": "多面刮削",
    "Scrape/Fill": "刮削填充",
    "Sharpen": "锐化",
    "Smear Multires Displacement": "涂抹置换",
    "Snake Hook": "蛇形钩",
    "Stretch/Move Cloth": "拉伸移动",
    "Thumb": "推挤",
    "Trim": "修剪",
    "Twist Boundary Cloth": "边界扭转",
    "Erase Hard Pressure": "硬感擦除",
    "Bend Boundary Cloth": "边界弯曲",
    "Bend/Twist Cloth": "弯曲扭转",
    "Erase Pixel Art": "擦除像素",
    "Paint Pixel Art": "绘制像素",
    "Scene Project":"场景投影",
    "Displaces vertices within the brush radius towards other objects in the scene, providing an effect similar to the Shrinkwrap modifier.":"将画笔半径内的顶点朝向场景中的其他对象位移，产生类似于收缩包裹修改器的效果。",
    "A soft round brush that builds up over time instead of stroke distance.": "一款柔边圆形笔刷，其效果随时间累积而非笔触距离增加。",
    "Bend only open boundaries of the mesh, folding the surrounding geometry in the process.": "仅对网格开放边界进行弯曲，同时折叠周围几何结构。",
    "A pose brush that rotates geometry.": "用于旋转几何体的姿势笔刷。",
    "Similar to Average brushes in other modes with a hard round falloff. Used to blend colors along the stroke.": "类似其他模式下的平均笔刷，采用硬边圆形衰减，可沿笔触混合颜色。",
    "Similar to Average brushes in other modes with a soft round falloff.": "类似其他模式下的平均笔刷，采用柔边圆形衰减。",
    "Similar to Average brushes in other modes with a hard square falloff.": "类似其他模式下的平均笔刷，采用硬边方形衰减。",
    "Magnifies the mesh as you draw. Useful for an additional inflation effect on the stroke.": "绘制时放大网格，可为笔触增添额外膨胀效果。",
    "Transform specifically mesh boundaries with various deformations.": "专用于网格边界的多种变形操作。",
    "Similar to the Draw brush but with a flattening effect and subtle smoothing. Useful for polishing and building volumes.": "类似绘制笔刷，但带有平整效果与轻微平滑，适用于打磨与体块构建。",
    "The same as the Clay brush, but more aggressive with a square falloff. A common standard for building rough volumes.": "与粘土笔刷相似，但采用方形衰减，塑形更为强烈，常用于构建粗犷体块。",
    "Specifically for emulating the effect of running your thumb over surfaces. Pushes geometry in and sideways.": "专为模拟拇指抹过表面的效果设计，可将几何体向内及侧向推挤。",
    "A Draw brush with a pinching effect. Useful for polishing existing creases or carefully creating new ones.": "带有捏合效果的绘制笔刷，适用于打磨现有折痕或精细创建新折痕。",
    "Much sharper and stronger Crease brush. Great for creating thin and deep pinches.": "更锐利、更强劲的折痕笔刷，适合制作薄而深的捏合效果。",
    "Cleans up geometry by collapsing short edges. Specifically for use with Dynamic Topology.": "通过合并短边清理几何结构，专为动态拓扑模式设计。",
    "Nudges the geometry along the surface while minimally affecting the overall shape of the object.": "沿表面轻推几何体，对整体形状影响极小。",
    "The standard brush for pushing vertices inwards and outwards from the surface direction.": "沿表面法向推拉顶点的标准绘制笔刷。",
    "Same as Draw but with a much sharper Falloff. Useful for creating creases and sharp angles.": "与绘制笔刷相同，但衰减更锐利，适合创建折痕与锐角。",
    "Used to simulate realistic deformations from grabbing of Elastic objects.": "用于模拟抓取弹性物体时的真实形变效果。",
    "Similar to Elastic Grab but rotates affected geometry based on the stroke direction.": "类似弹性抓取，但会依据笔触方向旋转受影响的几何体。",
    "Remove displacement information on a Multiresolution modifier.": "清除多级细分修改器上的位移信息。",
    "Creates compression or stretching on geometry.": "在几何体上产生压缩或拉伸形变。",
    "Paint new, smooth or extend existing Face Sets.": "绘制新面组、平滑或扩展现有面组。",
    "Pushes surfaces upwards towards a flat plane. Useful for filling in holes and crevices. Alternatively deepens existing holes.": "将表面向上推至平面，适合填补孔洞与缝隙；反向操作可加深现有孔洞。",
    "Pushes vertices to an average height to create a flat surfaces. Alternatively pushes them away from the center for more contrast.": "将顶点推至平均高度以创建平坦表面；反向操作可将顶点从中心推开以增强对比。",
    "Moves vertices along with the mouse. An essential brush for building shapes and adjusting proportions.": "随鼠标移动顶点，是塑造形态与调整比例的核心笔刷。",
    "Similar to Grab but with an infinitely projected falloff. Useful for grabbing broader shapes and giving a similar feel to using Liquify tools in image painting applications.": "类似抓取笔刷，但采用无限投影衰减，适合控制整体形态，体验类似图像处理中的液化工具。",
    "Grabs geometry within the brush radius firmly, while surrounding geometry is being simulated to follow.": "牢固抓取笔刷半径内的几何体，周围几何体通过物理模拟跟随移动。",
    "Similar to Grab Cloth but with a line as the brush radius instead of a circle.": "类似布料抓取笔刷，但使用直线而非圆形作为作用半径。",
    "Similar to Grab Cloth but with a noise texture applied to create more random variation.": "类似布料抓取笔刷，但应用噪波纹理以产生更随机的变形效果。",
    "Similar to Grab but only affects vertices with the normal facing sideways away from the view. Very useful for adjusting outer silhouettes of thin objects.": "类似抓取笔刷，但仅影响法线与视图方向垂直的顶点，非常适合调整薄型物体的外部轮廓。",
    "Inflates the geometry outwards or inwards.": "将几何体向外膨胀或向内收缩。",
    "Moves the mesh in multiple direction. Useful for inflating or shrinking surfaces and volumes.": "沿多方向移动网格，适用于膨胀或收缩表面与体块。",
    "Draw with a fixed height. Useful for adding flat layers to a surface.": "以固定高度绘制，适合为表面添加平坦层级。",
    "Paints a selection on parts of the mesh to be unaffected by other brushes.": "在网格局部绘制选区，使其不受其他笔刷影响。",
    "Similar as 'Thumb' but dynamically picks up vertices like the 'Snake Hook'. Useful for nudging something along the mesh surface.": "类似拇指笔刷，但动态吸附顶点如蛇形钩笔刷，适合沿网格表面精细推移物体。",
    "A mix of a 'Paint' and 'Blend' brush. On low pen pressure the brush averages colors and with high pen pressure it paints colors.": "绘画与混合功能结合的笔刷。低压感时混合颜色，高压感时绘制颜色。",
    "A simple hard round falloff brush for painting.": "用于绘画的简单硬边圆形衰减笔刷。",
    "A simple hard round falloff for painting.": "用于绘画的简单硬边圆形衰减笔刷。",
    "A hard round falloff with pressure sensitivity for the brush radius.": "笔刷半径具压感灵敏度的硬边圆形衰减笔刷。",
    "A soft round falloff with pressure sensitivity for only the strength.": "仅强度具压感灵敏度的柔边圆形衰减笔刷。",
    "A soft round falloff with pressure sensitivity for both radius and strength.": "半径与强度均具压感灵敏度的柔边圆形衰减笔刷。",
    "A hard square brush falloff for painting.": "用于绘画的硬边方形衰减笔刷。",
    "Pinches only from two perpendicular sides along the stroke direction, creating parallel folds along the stroke.": "沿笔触方向从两个垂直侧边收紧，形成平行褶皱。",
    "Pinches geometry to the center point of the radius, creating folds from all sides.": "将几何体向半径中心点收紧，从各方向形成褶皱。",
    "Pulls vertices towards the center of the brush. Useful for polishing angles and creases. Alternatively pushes them away from the center.": "将顶点拉向笔刷中心，适合锐化棱角与折痕；反向操作则将顶点从中心推开。",
    "Similar to Flatten but with a locked orientation and depth to create a consistently flat surface.": "类似展平笔刷，但具有锁定方向与深度，可创建均匀平坦表面。",
    "Simulating an armature-like deformations. Useful for quick posing and transformations.": "模拟类似骨骼的变形效果，适用于快速摆姿与形变。",
    "Iteratively picks up and lets go of geometry like the Snake Hook, but much softer. Useful for subtle small scale deforming over longer strokes.": "类似蛇形钩笔刷循环吸附与释放几何体，但作用更柔和，适合在长笔触上进行精细微调变形。",
    "Pushes geometry inwards or outwards.": "将几何体内压或外推。",
    "Similar to the Relax Slide brush but pinches/relaxes geometry instead.": "类似松弛滑动笔刷，但改为对几何体进行捏合/松弛处理。",
    "Slides the topology of the mesh in the direction of the stroke while preserving the geometrical shape of the mesh. Alternatively smoothes the mesh on 'Shift'. Also useful for redistributing topology where it is needed.": "沿笔触方向滑动网格拓扑并保持几何形状不变；按Shift键可平滑网格。也适用于重新分布拓扑至所需区域。",
    "Scrapes the mesh with two angled planes at the same time, producing a sharp edge between them.": "同时以两个倾斜平面刮削网格，在二者间形成锐利边沿。",
    "Pushes surfaces inwards. Alternatively fills surfaces while holding 'Ctrl'. This is the most common brush for flattening meshes.": "向内推挤表面；按住Ctrl键可填充表面。这是最常用的网格展平笔刷。",
    "Pinches the colors inwards to create sharp edges or points.": "将颜色向内收紧以形成锐利边沿或尖点。",
    "Smears colors along the stroke.": "沿笔触涂抹颜色。",
    "Smear displacement information on a Multiresolution modifier.": "在多级细分修改器上涂抹位移信息。",
    "Smooths out irregularities in the surface and shrinks volumes by averaging the vertices positions.": "通过平均顶点位置平滑表面不规则处并收缩体块。",
    "Pulls vertices along with the stroke to create long, snake-like forms. Geometry is rotated and magnified to allow continuous pulling. Ideally used with Dynamic Topology.": "沿笔触牵引顶点形成蛇形长管结构。通过旋转与放大几何体实现连续拉伸，建议配合动态拓扑使用。",
    "A pose brush that translates and scales geometry.": "可平移与缩放几何体的姿势笔刷。",
    "Same as 'Grab' but moves vertices along the surface direction. Useful for preserving specific surfaces.": "与抓取笔刷功能类似，但使顶点沿表面方向移动，适合保持特定表面结构。",
    "Pushes surfaces inwards toward a locked direction. The depth can be defined by going deeper towards surfaces along the stroke.": "将表面向内推向锁定方向，深度可通过沿笔触向表面深处移动来定义。",
    "Rotates vertices within the brush in the direction mouse.": "使笔刷范围内的顶点随鼠标方向旋转。",
    "Twist open boundaries of the mesh, creating twisting folds.": "扭转网格的开放边界，形成螺旋状褶皱。",
    "Blurs colors along the stroke.": "沿笔触模糊颜色。",
    "Use the 3D Cursor as a source position to clone textures from.": "使用3D游标作为克隆纹理的源位置。",
    "Erase the alpha channel of the texture with hard falloff.": "使用硬衰减擦除纹理的Alpha通道。",
    "Erase the alpha channel of the texture with hard falloff and pressure sensitivity for the radius.": "使用硬衰减与半径压感功能擦除纹理的Alpha通道。",
    "Erase the alpha channel of the texture with soft falloff.": "使用软衰减擦除纹理的Alpha通道。",
    "Fill the current color on visible and unmasked surfaces.": "在可见且未遮罩的表面上填充当前颜色。",
    "Blends all colors within the radius towards one color.": "将半径内所有颜色混合为单一颜色。",
    "Paint a set weight on vertices.": "在顶点上绘制指定权重。",
    "Smears weights along the stroke.": "沿笔触涂抹权重。",
    "Blurs weights along the stroke.": "沿笔触模糊权重。",
    "Blends all weights within the radius towards one color.": "将半径内所有权重混合为单一颜色。",
    "Erase pixels in the alpha channel of the texture (Only supported in the Image Editor)": "擦除纹理Alpha通道中的像素（仅在图像编辑器中支持）",
    "Paint specific pixels (Only supported in the Image Editor)": "绘制特定像素（仅在图像编辑器中支持）",
    "Blend Hair Curves": "混合头发",
    "Displace Hair Curves": "置换头发",
    "Frizz Hair Curves": "毛躁头发",
    "Hair Curves Noise": "头发噪波",
    "Roll Hair Curves": "卷起头发",
    "Rotate Hair Curves": "旋转头发",
    "Shrinkwrap Hair Curves": "缩裹头发",
    "Smooth Hair Curves": "平滑头发",
    "Straighten Hair Curves": "拉直头发",
    "Trim Hair Curves": "修剪头发",
    "Duplicate Hair Curves": "复制头发",
    "Generate Hair Curves": "生成头发",
    "Interpolate Hair Curves": "插值头发",
    "Braid Hair Curves": "编织头发",
    "Clump Hair Curves": "聚拢头发",
    "Create Guide Index Map": "创建映射",
    "Curl Hair Curves": "卷曲头发",
    "Curve Info": "曲线信息",
    "Curve Root": "曲线根部",
    "Curve Segment": "曲线段",
    "Curve Tip": "曲线尖端",
    "Hair Attachment Info": "头发信息",
    "Attach Hair Curves to Surface": "头发到面",
    "Redistribute Curve Points": "重分布点",
    "Restore Curve Segment Length": "恢复段长",
    "Set Hair Curve Profile": "头发轮廓",
    "Attaches hair curves to a surface mesh": "将头发曲线附着到曲面网格",
    "Blends shape between multiple hair curves in a certain radius": "在指定半径内混合多条头发曲线的形状",
    "Deforms existing hair curves into braids using guide curves": "使用引导曲线将现有头发曲线变形为辫子",
    "Clumps together existing hair curves using guide curves": "使用引导曲线将现有头发曲线聚拢在一起",
    "Creates an attribute that maps each curve to its nearest guide via index": "创建一个属性，通过索引将每条曲线映射到其最近的引导线",
    "Deforms existing hair curves into curls using guide curves": "使用引导曲线将现有头发曲线变形为卷发",
    "Reads information about each curve": "读取每条曲线的信息",
    "Reads information about each curve's root point": "读取每条曲线根点的信息",
    "Reads information each point's previous curve segment": "读取每个点的上一个曲线段的信息",
    "Reads information about each curve's tip point": "读取每条曲线尖端点的信息",
    "Displaces hair curves by a vector based on various options": "根据各种选项通过向量置换头发曲线",
    "Duplicates hair curves a certain number of times within a radius": "在指定半径内将头发曲线复制一定次数",
    "Deforms hair curves using a random vector per point to frizz them": "使用每个点的随机向量使头发曲线变形，产生毛躁效果",
    "Generates new hair curves on a surface mesh": "在曲面网格上生成新的头发曲线",
    "Reads attachment information regarding a surface mesh": "读取关于曲面网格的附着信息",
    "Deforms hair curves using a noise texture": "使用噪波纹理使头发曲线变形",
    "Interpolates existing guide curves on a surface mesh": "在曲面网格上插值现有的引导曲线",
    "Redistributes existing control points evenly along each curve": "沿每条曲线均匀重新分布现有的控制点",
    "Restores the length of each curve segment using a previous state after deformation": "变形后使用先前的状态恢复每个曲线段的长度",
    "Rolls up hair curves starting from their tips": "从尖端开始卷起头发曲线",
    "Rotates each hair curve around an axis": "绕轴旋转每条头发曲线",
    "Sets the radius attribute of hair curves according to a profile shape": "根据轮廓形状设置头发曲线的半径属性",
    "Shrinkwraps hair curves to a mesh surface from below and optionally from above": "将头发曲线从下方（可选择从上方）收缩包裹到网格曲面",
    "Smoothes the shape of hair curves": "平滑头发曲线的形状",
    "Straightens hair curves between root and tip": "在根部和尖端之间拉直头发曲线",
    "Trims or scales hair curves to a certain length": "将头发曲线修剪或缩放到指定长度"
}
