schema_version = "1.0.0"

id = "empty_collection_switcher"
version = "1.1.0"
name = "Empty & Collection Switcher"
tagline = "Convert collections and empties while keeping parent-child relationships"
maintainer = "CP-Design"
type = "add-on"

blender_version_min = "4.5.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

tags = ["Object", "User Interface"]
