# Dont change this, is not referred to addon version
schema_version = "1.0.0"
# Dont change this, is not referred to addon version


id = "playblast_puls"
version = "1.0.0"
name = "Playblast Puls \u5feb\u7167"
tagline = "\u5c06\u6e32\u67d3\u8bbe\u7f6e\u548c\u5feb\u7167\u8bbe\u7f6e\u5206\u5f00\u7ba1\u7406"
maintainer = "carlosmu | carlos.damian.munoz@gmail.com"
type = "add-on"
tags = ["Animation", "3D View", "User Interface", "Render"]
website = "https://blendermarket.com/products/playblast"

blender_version_min = "3.6.0"
license = ["SPDX:GPL-3.0-or-later",]